# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorData.proto',
  package='sensorid',
  serialized_pb=_b('\n\x10SensorData.proto\x12\x08sensorid\"l\n\x11SensorDataMessage\x12\x13\n\x0b\x64isplayname\x18\x01 \x02(\t\x12\x12\n\nsensorname\x18\x02 \x02(\t\x12.\n\rsensorreading\x18\x03 \x03(\x0b\x32\x17.sensorid.SensorReading\"C\n\rSensorReading\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12\t\n\x01x\x18\x02 \x02(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\x42\x14\n\x12\x64\x65.hszemi.sensorid')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENSORDATAMESSAGE = _descriptor.Descriptor(
  name='SensorDataMessage',
  full_name='sensorid.SensorDataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='displayname', full_name='sensorid.SensorDataMessage.displayname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensorname', full_name='sensorid.SensorDataMessage.sensorname', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensorreading', full_name='sensorid.SensorDataMessage.sensorreading', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=138,
)


_SENSORREADING = _descriptor.Descriptor(
  name='SensorReading',
  full_name='sensorid.SensorReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='sensorid.SensorReading.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='sensorid.SensorReading.x', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='sensorid.SensorReading.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='sensorid.SensorReading.z', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=207,
)

_SENSORDATAMESSAGE.fields_by_name['sensorreading'].message_type = _SENSORREADING
DESCRIPTOR.message_types_by_name['SensorDataMessage'] = _SENSORDATAMESSAGE
DESCRIPTOR.message_types_by_name['SensorReading'] = _SENSORREADING

SensorDataMessage = _reflection.GeneratedProtocolMessageType('SensorDataMessage', (_message.Message,), dict(
  DESCRIPTOR = _SENSORDATAMESSAGE,
  __module__ = 'SensorData_pb2'
  # @@protoc_insertion_point(class_scope:sensorid.SensorDataMessage)
  ))
_sym_db.RegisterMessage(SensorDataMessage)

SensorReading = _reflection.GeneratedProtocolMessageType('SensorReading', (_message.Message,), dict(
  DESCRIPTOR = _SENSORREADING,
  __module__ = 'SensorData_pb2'
  # @@protoc_insertion_point(class_scope:sensorid.SensorReading)
  ))
_sym_db.RegisterMessage(SensorReading)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022de.hszemi.sensorid'))
# @@protoc_insertion_point(module_scope)
